### ISSUE TITLE
Misc docs issues

### ISSUE THREAD

**Issue by osanseviero** [huggingface/hf-endpoints-documentation#47]
* A url in https://huggingface.co/docs/inference-endpoints/guides/custom_dependencies is not properly highlighted
* At the end of https://huggingface.co/docs/inference-endpoints/guides/custom_dependencies, we link to https://huggingface.co/docs/inference-endpoints/guides/custom_handler#3-customize-endpointhandler but it should link to https://huggingface.co/docs/inference-endpoints/guides/custom_container
* We link to https://huggingface.co/models?other=endpoints-template for templates, but there are more than 100. Should we change this to be a collection?

**Comment by Michellehbn** [comment]
Checking with @philschmid about the collections recommendation.

**Comment by Michellehbn** [comment]
Hi @osanseviero ! @philschmid and I are discussing best course of action for :

> We link to https://huggingface.co/models?other=endpoints-template for templates, but there are more than 100. Should we change this to be a collection?

I think we can close this issue in the meantime as done! Thanks again for reporting ❤️

**Comment by osanseviero** [comment]
LGTM!
