### ISSUE TITLE
Make more explicit that high availability/reliability requires >= 2 replica and add more explanations

### ISSUE THREAD

**Issue by MoritzLaurer** [huggingface/hf-endpoints-documentation#87]
See this [internal slack conversation](https://huggingface.slack.com/archives/C03E4DQ9LAJ/p1720618665351259?thread_ts=1720597567.656149&cid=C03E4DQ9LAJ) for context

**Comment by Michellehbn** [comment]
https://github.com/huggingface/hf-endpoints-documentation/pull/94
